language: python
python:
- 3.6
install:
- pip install -r requirements.txt
script:
- python -m unittest discover
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: NVLmF2FPd/rr2/7qBWtsGOqZa2Z/v4cXwckOFsd6ljA44UtHdmKws19Y8jHgc0O2Poeo6mm03gayZHmRUmVmI+vUmDp2FjqGBxYcV7o4iqVztseuwcVIz+FdxF13GCNcIoPLAEIcwJ7o7x5AgwEzRoZgelD0CCrOpkcXfSnFd69XbyjtE02FBL0ZVUYQfFgWJ+a6T4Molu3YI0PdCw4qQeE1X6W+KEV2PLyu0TkFvynwO7VqQAeqnkJnZglgLHfAr+dN645l2kX7l4cqbqu4vr+EK/8Aw+0Ao4y9JXSFIkqlb+nl6MfrRn5s/ZmgbpnCsv92kzl0OeywMpn7EHSFC7yCBbr4oUqWFI5OMNA322lcuubC2w0V1O8US4x6zROou0tWxxHOnpFHhfvDcg50M3XaQi2V8VjkvtwrKbSpiftRIl1JNS6M2EgBWF0Yneg0THZ9P+yosZNtaIbP8G4FcYIcWNoUD/xUMrrO40mem+8uHQuTNZWkX/hvHuCZsC5rbjEJMitfvY2ofqzzyN/2UUaHeC4ntJVuATv0fefbY23QXtjavRBwSWfpPRJK0twyJrRPnAzUVUYJqHDoVb1OWinWIcuc0J8lLMPSXVA2ivNNk7JRWYdRROxlo/LzoSscF/5YcaWI+r9QjoaDYYsy16nXzD7LUXz1JCWmW2zHzPQ=
  app: flight-line-bot
