language: python
python:
- 3.6
install:
- pip install -r requirements.txt
script:
- python -m unittest discover
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: MmEo/7cCHODUT5TmtMURg6RMEGmMrTa0mEAMLmUwl2EUIbI7gKLVKWz8UzLPpmN0O7f+XJ1oIzWI8wOx6LjKNjzShC2wWoh2Slt+HuiuHtAJWhOYwHS61Z8VisBY+kcCoCKzrYwJ0R93N9jnXfyr5aibAA1J8hXXjDZTuX2AL/6BFJPgbVDIxLdKhFKjfatyD5N1duI7X/yiSfM6jnkTYfoeQrOlnbBeW4RB3YjI+3OeRy1YtSA9cLGeDzaQrZABfLOiVJCiokuzTv9GxIlEjQEp9lO5hd2CY6PQS+22j8jQ3Q+PjYhUEW2fB4lnjwCKdcOd+5Gj7Ru2w/8aWrd9o5jFk6/i0fHzcXGQOetRKiEbb81e+F55K0yQEVe4aEeJI7NN3CQa1KKfl2pwzOPjwE/9okIjYjTnvT7tKUcgAxnyO8beXmUHK8G2wRLHc+lixKYX/cC+V+4QrTTC3mS5+w5pZw5lCwyx7te16mVNAubVyAxF2ewGEAjGnPfbaKXUThRgnU1GEZvKhfPo4Gj+VDQAncY94NZHcZ6DfG+gsgTZK4ny+uovMTN2OyUIWfxO7bHZBtLK/INj/dzIrLKTRxpzGdWkoKaL+1WgPWVGCSAwxy6l+cXUTOafLvYU5JjijCccLqn2zyCWjkjPkxENgWqnUgGSSuUo8mMQSDpRtw0=
  app: line-flight-bot
