language: python
python:
- 3.6
install:
- pip install -r requirements.txt
script:
- python -m unittest discover
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: Z4o4+fOKqGvFm8vPOxK3ENS9RkMtt9CLFu3TkVT3LpruWbnFeXqbgJjQROC6aAc8gnr4Fj6pyVGQUO+0uhLt9QMBe+SU2JUKmrBr/CYMI4M8QpDqOmBAEOTANB5tRXAFuW3+uAh13VnENTj9SXGbDO7oz5zaZ5KD+IrL+ngiTpdBkpDUMhv2PtDrLuIAklI3TedMoC5p4IkUYFaO+dtPS7KzEC1eiLIj1P+9jhr4E6HBv80wIqo+w7T+FQ3t/OBVc6xC8r1qG1ALP8ngVHvbHggaJrbejNMC7lcGuQvmo5cgRRUGLpVrCqFOWs4EliETN9bTRzm1FM6gFOhRK6rmyBsZj/Ibmza2yqz0FYB67YaEA86WLHfF8SAcbpNOXzMhvzXrY2tPIYodmd350hi/zq0pEpZPZVzC+EX8Y2SP1WFEy9n4mQpsvprV0ShvAToH7PCcTAblfcW5fmp4wtk9yNjI8q7jRe8/NVkO+kGua8SuOqKj/gsVDK9B6Tt1ilj3bxJm/ukUw86cMSxNHT018CMLb5kJ0rTbN1cONuAmfBcUG3MeQEwBpzIOMsUer/zMUFc2uVVqQSvPBTspT4ZjInXTHvDGuMZ2PTuYw3J0DGbkrnlYDINZQ+rNAAy6a9ZlczrMh3F0P/gQA4U9IwZeuzHU3deE8Vk0HGXcdzl3ipg=
  app: line-flight-bot
