language: python
python:
- 3.6
install:
- pip install -r requirements.txt
script:
- python -m unittest discover
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: n+zD5eV5ReObHgO+ZtHcUfTa5I0ShSMvn2qNQ3AouuVYLMa7ZtjwH6lxiI7qPJjf60eh7ZDYBHUJsVe1GaQ44E9/2B3IBKUsHt4obsHdj81OLIkFpsUFwMq6EqQbI4QfDiu5plwjO35Is357WVmHMd+FNKpvimNigRv0L1ANr1OgEk+Tjp/ESThbxORmWC5/IdTC8NWxVA4WkKnCWB/MO+a9o34i9Uygu0TjU0AkMs3blicdNadZGD7wiVMC8RZduw3vqILQ39a/WSirPRhTe1gVFILmVAStbAmlEN2qoPSu8G1jWl07fn60XmmFaSm9gm3EBxlXeGCtLy44chveVHhRUaoyagkI9QX798G17iYwD+IJfatEHIfd4AYJ89mTNewg3OwFrHo0CvomsJyK9E9hL2bokruct9zBM01U3s410QL+ZsktaKyjwNkm0vF74jD169nvHxY9jTsP7vz60/xfuRi33DG7X0qFJCqx8GCPyoskKw7hV4Rlw2cyqALEgWI5uKnBm3rJDaOcebNx7Y+Oj2oNw7XCMvb/23fwgKOSfcXLWYw3MqIDU/HGPDdDa/HSwd4s/vJ2vvUkg0lupp4zXNYR2PiTBQXAB7qzM0kfrC/nHVh8zHWIEryuuS8hyggcQ1gxt6hGg4qKMUjdi4OovKf20MQIgVQ1BwZ4Su0=
  app: line-flight-bot
